### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Jawz84** [devops-collective-inc/big-book-of-powershell-gotchas#5]
Hello @concentrateddon, others,

I cloned this repo, created a branch, committed something, and wanted to push my branch back as a Pull request, but I get 403 access denied. What's your preferred flow?

``` git
> git push -u origin Remove_GitBook_references
remote: Permission to devops-collective-inc/big-book-of-powershell-gotchas.git denied to Jawz84.
fatal: unable to access 'https://github.com/devops-collective-inc/big-book-of-powershell-gotchas.git/': The requested URL returned error: 403
```

Thanks :)

**Comment by concentrateddon** [comment]
Um. Weird. I know we've gotten PRs to this repo before with no problem, so not sure. Google (https://github.com/github/VisualStudio/issues/1361) suggests that it might just be an authentication issue and logging out/in might help?

**Comment by Jawz84** [comment]
Ok thx, will check later. As a matter of fact, I did start using a different MFA app for GitHub this morning. Maybe that's it then.

**Comment by Jawz84** [comment]
I found my problem.    
My flow was: go to this repo, clone it in VSCode, create a branch, do commit, try push branch back to this repo. I am not allowed to do that: 403.   

Solution:  
My flow needed to be: Fork this repo to my own GitHub, clone it in VSCode, do commit, push to my repo, create merge request on my GitHub page.
